apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba-deploy
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: prueba-deploy
  template:
    metadata:
      labels:
        app: prueba-deploy
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80