name: My Reusable Workflow

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        default: ''

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables
        id: env
        run: |
          echo "ENVIRONMENT=development" >> $GITHUB_ENV
          echo "CONFIG_FILE=configuration.json" >> $GITHUB_ENV

      - name: Read configuration from JSON
        run: |
          ENVIRONMENT=${{ env.ENVIRONMENT }}
          CONFIG_FILE=${{ env.CONFIG_FILE }}
          echo "Using environment: $ENVIRONMENT"
          echo "Using config file: $CONFIG_FILE"
          # Use jq or any other tool to parse JSON and extract values based on the environment
          # For example:
          # VALUE1=$(jq -r ".[$ENVIRONMENT].value1" $CONFIG_FILE)
          # VALUE2=$(jq -r ".[$ENVIRONMENT].value2" $CONFIG_FILE)
          # echo "Value 1: $VALUE1"
          # echo "Value 2: $VALUE2"
